name: PR Build

on:
  pull_request:
      branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [6.0.x, 7.0.x, 8.0.x,9.x]

    steps:
    - uses: actions/checkout@v4
      
    - name: Emit .NET 6.0 Framework Moniker
      if: matrix.dotnet-version == '6.0.x'
      run: echo "DOTNET_FX_VERSION=net6.0" >> $GITHUB_ENV

    - name: Emit .NET 7.0 Framework Moniker
      if: matrix.dotnet-version == '7.0.x'
      run: echo "DOTNET_FX_VERSION=net7.0" >> $GITHUB_ENV

    - name: Emit .NET 8.0 Framework Moniker
      if: matrix.dotnet-version == '8.0.x'
      run: echo "DOTNET_FX_VERSION=net8.0" >> $GITHUB_ENV

    - name: Emit .NET 9.0 Framework Moniker
      if: matrix.dotnet-version == '9.0.x'
      run: echo "DOTNET_FX_VERSION=net9.0" >> $GITHUB_ENV

    - name: Setup .NET ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Install dependencies
      run: dotnet restore -p:TargetFrameworks=${{ env.DOTNET_FX_VERSION }}

    - name: Build
      run: dotnet build -c Release --no-restore -f ${{ env.DOTNET_FX_VERSION }}

    - name: Test
      run: dotnet test -c Release --no-build --no-restore -f ${{ env.DOTNET_FX_VERSION }}
